recepcion:
    resource: "@RecepcionBundle/Controller/"
    type:     annotation
    prefix:   /

acceso:
    resource: "@AccesoBundle/Controller/"
    type:     annotation
    prefix:   /
    
modelo:
    resource: "@ModeloBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    path:     /login
    defaults: { _controller: AccesoBundle:Acceso:login }

login_check:
    path: /login_check

logout:
    path: /logout