# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory: 
            memory:
                users:
                    isabel:
                        password: 1234

        user_db_provider:
            entity:
                class: ModeloBundle:Usuario
                property: username
    
    encoders:

        ModeloBundle\Entity\Usuario:
            algorithm: bcrypt
        
        #Symfony\component\Security\Core\User\User: plaintext
        #ModeloBundle\Entity\Usuario: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        topico:
            anonymous: ~
            pattern: ^/
            provider: user_db_provider
            form_login:
                login_path: /login
                check_path: /login
                default_target_path: /panel

            http_basic: ~
            logout:
                path: /logout
                target: /login


        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html


    access_control:
        - {path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^(/doctor|/recepcion|/|/mantenimiento|/), roles: [ROLE_DOCTOR,ROLE_RECEPCIONISTA]}