<?php

namespace ModeloBundle\Repository;

/**
 * SeguroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeguroRepository extends \Doctrine\ORM\EntityRepository
{
}
