<?php

namespace ModeloBundle\Repository;

/**
 * TantecedenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TantecedenteRepository extends \Doctrine\ORM\EntityRepository
{
    //  FUNCION 
    public function Data_Items($codper) {
        $sql = "SELECT  [cod_tantecedente] AS codigo ,
                        [tant_descripcion] AS descripcion ,
                        ISNULL(( SELECT COUNT(cod_antecedente)
                                 FROM   [Topico].[dbo].[Antecedente] AS t2
                                 WHERE  t2.codper = $codper
                                        AND t2.cod_tantecedente = t1.cod_tantecedente
                               ), 0) AS cantidad ,
                        [tant_estado]
                FROM    [Topico].[dbo].[Tantecedente] AS t1
                WHERE   t1.tant_estado = 1; ";
        
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();
        $datos = $stmt->fetchAll();
        return $datos;
    }
    //  FUNCION 
    public function Data_Items_cantidades($codper) {
        $sql="SELECT  t1.cod_tantecedente as cod,ISNULL(( SELECT COUNT(cod_antecedente)
                                FROM   [Topico].[dbo].[Antecedente] AS t2
                                WHERE  t2.codper = $codper
                                       AND t2.cod_tantecedente = t1.cod_tantecedente
                              ), 0) AS cantidad
               FROM    [Topico].[dbo].[Tantecedente] AS t1
               WHERE   t1.tant_estado = 1;";
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();
        $datos = $stmt->fetchAll();
        return $datos;
    }
}
