<?php

namespace ModeloBundle\Repository;

/**
 * EstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TdiagnosticoRepository extends \Doctrine\ORM\EntityRepository
{
}
