<?php

namespace ModeloBundle\Repository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository
{
   //  FUNCION PARA SESSION DEL USUARIO PARAMETRO CODIGO PERSONA
    public function Data_usuario_by_cod($codper) {
        $sql = " SELECT  t1.cod_user AS codigo ,
                        t1.percodigo AS codper ,
                        t1.user_perfil AS codperf ,
                        t2.cLe AS dni ,
                        ( CASE t1.user_perfil
                            WHEN 1 THEN 'Recepcion'
                            WHEN 2 THEN 'Doctor'
                          END ) AS perfil ,
                        t2.cNombres AS nombres ,
                        t2.cApePat AS apaterno ,
                        t2.cApeMat AS amaterno
                FROM    Topico.dbo.Usuario AS t1
                        INNER JOIN dbo.Trabajador AS t2 ON t1.percodigo = t2.nCodTra
                        WHERE   t2.nCodTra = '$codper';";

        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();
        $datos = $stmt->fetch();
        return $datos;
    }
}
